FROM golang:1.23.2-alpine

WORKDIR /app

RUN apk add --no-cache git

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY .air.toml .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
