services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    volumes:
      - .:/app
      - ${HOME}/.aws:/root/.aws:ro
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - PORT=8080
    tty: true
    stdin_open: true
